REPORT ZCARGE_CSV.

INCLUDE ZBDCRECX1_S."Z Version of include
INCLUDE ZCARGE_CSV_TOP."Declarations
INCLUDE ZCARGE_CSV_S01."Selection Screen
INCLUDE ZCARGE_CSV_F01."Functions

START-OF-SELECTION.

PERFORM PRINCIPAL."Main process