SELECTION-SCREEN FUNCTION KEY 1.

PARAMETERS: P_FILE TYPE DYNPREAD-FIELDNAME.

AT SELECTION-SCREEN OUTPUT.

LOOP AT SCREEN.
    IF SCREEN-NAME EQ 'P_FILE' OR SCREEN-NAME EQ '%_P_FILE_%_APP_%-TEXT'.
       CONTINUE.
    ELSE.
        SCREEN-ACTIVE = 0.
        MODIFY SCREEN.
    ENDIF.
ENDLOOP.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR P_FILE.

CALL FUNCTION 'F4_FILENAME'
  EXPORTING
      PROGRAM_NAME = SYST-CPROG
      DYNPRO_NUMBER = SYST-DYNNR
  IMPORTING
      FILE_NAME = VL_FILE.

      P_FILE = VL_FILE.

INITIALIZATION.

VL_SEL_BUTTON-ICON_ID = ICON_WD_VIEW_SET_GRID.

VL_SEL_BUTTON-TEXT = TEXT-B01.
VL_SEL_BUTTON-ICON_TEXT = TEXT-B01.

SSCRFIELDS-FUNCTXT_01 = VL_SEL_BUTTON.